In [1]:
# Atribuindo o código de cada pacote à uma variável e depois em uma lista com todos os pacotes

cod1 = "888555555123888"
cod2 = "333333555584333"
cod3 = "222333555124000"
cod4 = "000111555874555"
cod5 = "111888555654777"
cod6 = "111333555123333"
cod7 = "555555555123888"
cod8 = "888333555584333"
cod9 = "111333555124000"
cod10 = "333888555584333"
cod11 = "555888555123000"
cod12 = "111888555123555"
cod13 = "888000555845333"
cod14 = "000111555874000"
cod15 = "111333555123555"

lista = [cod1,cod2,cod3,cod4,cod5,cod6,cod7,cod8,cod9,cod10,cod11,cod12,cod13,cod14,cod15]

In [2]:
# importando biblioteca para separar os códigos de barra
from textwrap import wrap

# definindo função para "cortar" os códigos de barra

def corta(x):
    
    # criando lista vazia para guardar os códigos cortados
    cortados = []
    
    # loop levando em conta a quantidade de pacotes
    for n in range(0,len(x)):
        
        # usando função "wrap" para "cortar" o código a cada 3 caracteres
        y = wrap(x[n],3)
        
        # adicionando o código de barra "cortado" à lista "cortados"
        cortados.append(y)
    
    # retornando a lista completa
    return cortados

# aplicando função à lista de códigos feita e salvando em uma variável
cortado = corta(lista)

In [3]:
# importando biblioteca pandas para se trabalhar com os dados
import pandas as pd

# criando um DataFrame com as os códigos de barra "cortados" e com a devida ordem de Trincas
df1 = pd.DataFrame(cortado, columns =["Região de Origem",
                                   "Região de Destino",
                                   "Código da Loggi",
                                   "Código do Vendedor do produto",
                                   "Tipo do produto"])

# Começando a indexação com 1
df1.index += 1

# os índices representam o número do pacote
df1

,Região de Origem,Região de Destino,Código da Loggi,Código do Vendedor do produto,Tipo do produto
1,888,555,555,123,888
2,333,333,555,584,333
3,222,333,555,124,000
4,000,111,555,874,555
5,111,888,555,654,777
6,111,333,555,123,333
7,555,555,555,123,888
8,888,333,555,584,333
9,111,333,555,124,000
10,333,888,555,584,333
11,555,888,555,123,000
12,111,888,555,123,555
13,888,000,555,845,333
14,000,111,555,874,000
15,111,333,555,123,555

In [4]:
# Precisa-se aplicar filtros para que as restrições sejam cumpridas

In [5]:
# 1) A Loggi não envia produtos que não sejam dos tipos acima informados.

# Lista com as strings aceitas para Tipo de Produto
valores_aceitos = ["000","111","333","555","888"]

# Selecionando apenas os valores que estão na lista de valores aceitos
df = df1[df1["Tipo do produto"].isin(valores_aceitos)]

In [6]:
# 2) Não é possível despachar pacotes contendo jóias tendo como região de origem o Centro-oeste;

# Retirando os códigos de Região não aceitos


# Lista com as strings aceitas para Região
valores_aceitos = ["000","111","333","555","888"]

# Selecionando apenas os valores que estão na lista de valores aceitos
df = df[df["Região de Origem"].isin(valores_aceitos)]
df = df[df["Região de Destino"].isin(valores_aceitos)]

In [7]:
# Substituindo valores do código pelos nomes das regiões usando um dicionário

# Região

regiao = {"111" : 'Centro-oeste', "333" : 'Nordeste', "555" : 'Norte', "888" : 'Sudeste', "000" :"Sul"}

df["Região de Origem"].replace(regiao, inplace=True)

df["Região de Destino"].replace(regiao, inplace=True)


# Substituindo valores do código pelos nomes dos produtos usando um dicionário

# Tipo de Produto

produto = {"000" : 'Jóias', "111" : 'Livros', "333" : 'Eletrônicos', "555" : 'Bebidas', "888" :"Brinquedos"}

df["Tipo do produto"].replace(produto, inplace = True)

In [8]:
# Removendo linhas onde Região é "Centro-oeste" e onde o produto é "Jóias"

df = df.loc[~((df['Região de Origem'] == "Centro-oeste") & (df['Tipo do produto'] == "Jóias")),:]

In [9]:
# 3) O vendedor 584 está com seu CNPJ inativo, códigos de barra relacionados a este vendedor devem ser considerados inválidos.

# Lista com as strings rejeitadas para Código do Vendedor do produto
valores_rejeitados = ["584"]

# Excluindo apenas os valores que estão na lista de valores rejeitados
df = df[~df["Código do Vendedor do produto"].isin(valores_rejeitados)]

In [10]:
# Tarefas

In [11]:
# a) Identificar o destino de cada pacote.

df1["Região de Destino"].replace(regiao, inplace=True)
df1["Região de Destino"]

# à esquerda o nº do pacote e à direita seu destino

1            Norte
2         Nordeste
3         Nordeste
4     Centro-oeste
5          Sudeste
6         Nordeste
7            Norte
8         Nordeste
9         Nordeste
10         Sudeste
11         Sudeste
12         Sudeste
13             Sul
14    Centro-oeste
15        Nordeste
Name: Região de Destino, dtype: object

In [12]:
# b) Saber quais pacotes possuem códigos de barras válidos e/ou inválidos.

# os códigos válidos estão no daframe "df"

# número dos pacotes válidos
df.index

Int64Index([1, 4, 6, 7, 11, 12, 13, 14, 15], dtype='int64')

In [13]:
from collections import Counter

c1 = Counter(df1.index)
c2 = Counter(df.index)

diff = c1-c2

# número dos pacotes inválidos
print(list(diff.elements()))

[2, 3, 5, 8, 9, 10]

In [32]:
# c) Identificar se algum pacote que tem como origem a região Sul tem Brinquedos em seu conteúdo.

sul_brin = df.loc[((df['Região de Origem'] == "Sul") & (df['Tipo do produto'] == "Brinquedos"))]

if not sul_brin.empty == False:
    print("Nenhum pacote tem como origem a região Sul e tem Brinquedos em seu conteúdo")
else:
    print("Há pacotes com origem na região Sul com Brinquedos em seu conteúdo")

Nenhum pacote tem como origem a região Sul e tem Brinquedos em seu conteúdo

In [50]:
# d) Listar os pacotes agrupados por região de destino (Considere apenas pacotes válidos).

df.groupby("Região de Destino").apply(lambda a: a[:])

                     Região de Origem Região de Destino Código da Loggi  \
Região de Destino
Centro-oeste      4               Sul      Centro-oeste             555
                  14              Sul      Centro-oeste             555
Nordeste          6      Centro-oeste          Nordeste             555
                  15     Centro-oeste          Nordeste             555
Norte             1           Sudeste             Norte             555
                  7             Norte             Norte             555
Sudeste           11            Norte           Sudeste             555
                  12     Centro-oeste           Sudeste             555
Sul               13          Sudeste               Sul             555

                     Código do Vendedor do produto Tipo do produto
Região de Destino
Centro-oeste      4                            874         Bebidas
                  14                           874           Jóias
Nordeste          6                            123     Eletrônicos
                  15                           123         Bebidas
Norte             1                            123      Brinquedos
                  7                            123      Brinquedos
Sudeste           11                           123           Jóias
                  12                           123         Bebidas
Sul               13                           845     Eletrônicos

In [71]:
# e) Listar o número de pacotes enviados por cada vendedor (Considere apenas pacotes válidos).

# À esquerda o código do vendedor, à direita o número de pacotes enviados por ele
df.pivot_table(index=['Código do Vendedor do produto'], aggfunc='size')

Código do Vendedor do produto
123    6
845    1
874    2
dtype: int64

In [17]:
# f) Gerar o relatório/lista de pacotes por destino e por tipo (Considere apenas pacotes válidos).

df[["Região de Destino","Tipo do produto"]]

   Região de Destino Tipo do produto
1              Norte      Brinquedos
4       Centro-oeste         Bebidas
6           Nordeste     Eletrônicos
7              Norte      Brinquedos
11           Sudeste           Jóias
12           Sudeste         Bebidas
13               Sul     Eletrônicos
14      Centro-oeste           Jóias
15          Nordeste         Bebidas